package in.sp.main.service;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import in.sp.main.entity.Ticket;
import in.sp.main.exceptions.NoSuchTicketException;
import in.sp.main.repositories.TicketRepository;

@Service
public class TicketServiceImpl implements TicketService{
	
	private final Logger log = LoggerFactory.getLogger(TicketServiceImpl.class);
	
	@Autowired
	private TicketRepository ticketRepository;

	@Override
	@Transactional
	public Ticket insertTicket(Ticket ticket) {
		// TODO Auto-generated method stub
		ticket.setTicketId(null); // As ID is auto generated by the DB (if we do not set it as null then
		                          // the LLM will even ask for ID)
		Ticket save = ticketRepository.save(ticket);
		log.info("Successfully saved entity");
		return save;
	}

//	@Override
//	public Ticket getTicketById(Long ticketId) {
//		// TODO Auto-generated method stub
//		Ticket ticket = ticketRepository
//				.findById(ticketId)
//				.orElseThrow(() -> new NoSuchTicketException("There's no ticket with id : " + ticketId));
//		
//		log.info("Successfully retrieved entity");
//
//		return ticket;
//	}

	@Override
	public Ticket getTicketByEmail(String email) {
		// TODO Auto-generated method stub
		Ticket ticket = ticketRepository
				.findByEmail(email)
				.orElseThrow(() -> new NoSuchTicketException("There's no ticket with email : " + email));
		
		log.info("Successfully retrieved entity");

		return ticket;
	}


	@Override
	@Transactional
	public Ticket updateTicketByEmail(String email, Ticket updatedTicket) {
		// TODO Auto-generated method stub
		Ticket ticket = ticketRepository
				        .findByEmail(email)
				        .orElseThrow(() -> new NoSuchTicketException("There's no ticket with email : " + email));
		
		if (updatedTicket.getTicketSummary() != null) ticket.setTicketSummary(updatedTicket.getTicketSummary());
		if (updatedTicket.getPriority() != null) ticket.setPriority(updatedTicket.getPriority());
		if (updatedTicket.getCategory() != null) ticket.setCategory(updatedTicket.getCategory());
		if (updatedTicket.getDescription() != null) ticket.setDescription(updatedTicket.getDescription());
//		if (updatedTicket.getEmail() != null) ticket.setEmail(updatedTicket.getEmail());
		if (updatedTicket.getStatus() != null) ticket.setStatus(updatedTicket.getStatus());
		
		log.info("Successfully updated entity");
		
		return ticketRepository.save(ticket);
		
	}

	@Override
	@Transactional
	public void deleteTicketByEmail(String email) {
		// TODO Auto-generated method stub
		Ticket ticket = ticketRepository
		        .findByEmail(email)
		        .orElseThrow(() -> new NoSuchTicketException("There's no ticket with email : " + email));
		
		
		ticketRepository.delete(ticket);
		
		log.info("Successfully deleted entity");

	}

}
